### ISSUE TITLE
Hi，JianZhu, the result of aflw is different from your?

### ISSUE THREAD

**Issue by xiaoxingzeng** [cleardusk/3DDFA#4]
My command line is : python benchmark.py -c models/phase1_wpdc_vdc.pth.tar (I use python 2.7 instead)
![qq 20180810222913](https://user-images.githubusercontent.com/22523429/43963571-3a61eb0e-9ced-11e8-9929-36e97accae1a.jpg)

The result of AFLW2000 is similar with yours ,but the other one is far away from result your presented.
So, what problem I encounted?

Thanks JianZhu for your contribution!

**Comment by cleardusk** [comment]
The may be some bugs for testing。To check the version problem, you should use Pytorch 0.4 or 0.4.1 and Python 3.6, as the code is only tested on these environments. I have run it on several different servers with the same pytorch and python version, the results are all the same as reported。

**Comment by zhww** [comment]
> My command line is : python benchmark.py -c models/phase1_wpdc_vdc.pth.tar (I use python 2.7 instead)
> ![qq 20180810222913](https://user-images.githubusercontent.com/22523429/43963571-3a61eb0e-9ced-11e8-9929-36e97accae1a.jpg)
> 
> The result of AFLW2000 is similar with yours ,but the other one is far away from result your presented.
> So, what problem I encounted?
> 
> Thanks JianZhu for your contribution!

Hi， I got the same result as you, have you changed the env to Pytorch 0.4  and  Python 3.6 and then check the result again?

**Comment by cleardusk** [comment]
Hi, the default env of this project is exactly Pytorch 0.4 and Python 3.6.

**Comment by yuxwind** [comment]
@zhww @xiaoxingzeng I noticed that both s4 and s5 are calculated in evaluate/benchmark_aflw.py and evaluate/benchmark_aflw2000.py. s4 is commented out and s5 is reported. However, the overall NME should be s4. 

I checked the consistency of AFLW_GT_pts68.npy and AFLW_GT_pts21.npy.  I got the pseudo 21 landmarks from AFLW_GT_pts68.npy by `ind_68to21` and calculated the euclidian distance between pseudo 21 landmarks and GT 21 landmarks. After filtering out the invalid landmarks, the average distance is 10.21. 

I also observed the test error on AFLW is much larger. As the network is supervised by 68 landmarks in 300w-LP, it probably also learn to approach  AFLW_GT_pts68.npy instead of AFLW_GT_pts21.npy. If so, can this explain the large test error on AFLW?
