### ISSUE TITLE
Problem about rendering

### ISSUE THREAD

**Issue by wosecz** [cleardusk/3DDFA#48]
Thank you very much for your work!
Actually I run your code successfully, the structure of the code is extremely clear.
However, when I use MeshLab to visualize the .obj and .pyl, I find the  rendering result is confusing:
![image](https://user-images.githubusercontent.com/10692992/53406703-9e390180-3a0e-11e9-9bd4-df7e3b132a87.png)
![image](https://user-images.githubusercontent.com/10692992/53406730-a85b0000-3a0e-11e9-9f57-ed9fc9b829c8.png)
It seems that the 3D model(.pyl files) is partially normal.
Did I do something wrong? Or should I try another visualization tool?
By the way ,don't you think the 3D models(.obj files) look similar? 
![image](https://user-images.githubusercontent.com/10692992/53407008-451d9d80-3a0f-11e9-994e-01f03a648a55.png)

Thank you very much!

**Comment by cleardusk** [comment]
1. The rendering issue is described in [FQA](https://github.com/cleardusk/3DDFA#fqa): the texture of non-visible area is distorted due to self-occlusion.
2. The 3D face reconstruction of this method may be not so high-fidelity. If you are interested, you can refer to papers for high-fidelity face reconstruction.
